### ISSUE TITLE
lable:question Is this module a performance boost?

### ISSUE THREAD

**Issue by benzmuircroft** [npm/multi-fs#4]
I would like to see fs do things a lot faster! I need to fs.writeFile 112 times (writing separate png files) once every 13 seconds. I want to do this in a for loop with fs writing each whole file regardless of weather it has finished writing the previous.

Normally fs would start to write the file and **have to** complete the job before it can begin to write the next. Just so I absolutly understand what you have made...does your module let fs multitask when writing in a for loop?

Thanks

**Comment by soldair** [comment]
If you use the async methods of fs instead of the sync your code will perform multiple concurrent file system operations. This may make your code faster. 

this module is used to copy files to remote servers.

because this issue is not related to multifs itself im going to close it.
